name: Tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 10 * * *

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        run: npm run jest-test

      - name: Upload Test Results
        uses: trunk-io/analytics-uploader@main
        # Upload the results even if the tests fail
        if: "!cancelled()"
        with:
          junit-paths: "**/*_test.xml,**/junitresults-*.xml"
          # Provide your Trunk organization slug.
          org-slug: katherines-org
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
        # don't fail this job if the upload fails
        continue-on-error: true
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io

      - name: Upload test results with default CLI version to dev3
        if: "!cancelled()"
        continue-on-error: true
        uses: trunk-io/analytics-uploader@main
        with:
          org-slug: katherines-org
          token: ${{ secrets.TRUNK_DEV_3_ORG_API_TOKEN }}
          junit-paths: "**/*_test.xml,**/junitresults-*.xml"
          quarantine: true
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.dev3.trunk-staging.io
