name: Tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        uses: trunk-io/analytics-uploader@main
        with:
          # Path to your test results.
          junit-paths: "**/*_test.xml,**/junitresults-*.xml"
          # Provide your Trunk organization slug.
          org-slug: katherines-org
          # Provide your Trunk API token as a GitHub secret.
          token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
          run: npm run jest-test
